Hello

In [ ]:
import torch
print(torch.__version__)

2.5.1+cu121


In [ ]:
MATRIX = torch.tensor([[[7, 8, 10, 11],
                       [9, 10, 12, 13]]])

In [ ]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1524, 0.5969, 0.3371, 0.5435],
        [0.1851, 0.7163, 0.6972, 0.0521],
        [0.9748, 0.8880, 0.9088, 0.2006]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor

tensor([[[0.7840, 0.7266, 0.2558,  ..., 0.4587, 0.2315, 0.4998],
         [0.3644, 0.7824, 0.2864,  ..., 0.9012, 0.5989, 0.6845],
         [0.0069, 0.9309, 0.9598,  ..., 0.3273, 0.9336, 0.6332],
         ...,
         [0.3501, 0.2645, 0.4313,  ..., 0.4386, 0.4276, 0.3406],
         [0.5621, 0.9550, 0.2754,  ..., 0.9430, 0.3102, 0.8119],
         [0.2118, 0.9316, 0.0708,  ..., 0.7607, 0.1871, 0.7134]],

        [[0.9975, 0.0313, 0.1347,  ..., 0.6985, 0.3552, 0.1062],
         [0.2495, 0.0769, 0.5793,  ..., 0.9519, 0.5043, 0.7290],
         [0.5687, 0.4959, 0.8387,  ..., 0.3980, 0.0368, 0.8708],
         ...,
         [0.6288, 0.1330, 0.8687,  ..., 0.1733, 0.3102, 0.5618],
         [0.1119, 0.6617, 0.5292,  ..., 0.4600, 0.9825, 0.4651],
         [0.4317, 0.2113, 0.4513,  ..., 0.7310, 0.6961, 0.3750]],

        [[0.9128, 0.3187, 0.4027,  ..., 0.8587, 0.1289, 0.7847],
         [0.3298, 0.5224, 0.7070,  ..., 0.2566, 0.4167, 0.9802],
         [0.1893, 0.4403, 0.1002,  ..., 0.5436, 0.9545, 0.

In [ ]:
zero = torch.zeros(3, 4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
 minus_7_from_1000 = torch.arange(start=1000, end=0, step=-7)
 minus_7_from_1000

tensor([1000,  993,  986,  979,  972,  965,  958,  951,  944,  937,  930,  923,
         916,  909,  902,  895,  888,  881,  874,  867,  860,  853,  846,  839,
         832,  825,  818,  811,  804,  797,  790,  783,  776,  769,  762,  755,
         748,  741,  734,  727,  720,  713,  706,  699,  692,  685,  678,  671,
         664,  657,  650,  643,  636,  629,  622,  615,  608,  601,  594,  587,
         580,  573,  566,  559,  552,  545,  538,  531,  524,  517,  510,  503,
         496,  489,  482,  475,  468,  461,  454,  447,  440,  433,  426,  419,
         412,  405,  398,  391,  384,  377,  370,  363,  356,  349,  342,  335,
         328,  321,  314,  307,  300,  293,  286,  279,  272,  265,  258,  251,
         244,  237,  230,  223,  216,  209,  202,  195,  188,  181,  174,  167,
         160,  153,  146,  139,  132,  125,  118,  111,  104,   97,   90,   83,
          76,   69,   62,   55,   48,   41,   34,   27,   20,   13,    6])

In [12]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [13]:
x_reshaped = x.reshape(3, 3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [14]:
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [15]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [23]:
x_stacked = torch.stack([x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.],
        [5., 5., 5.],
        [6., 6., 6.],
        [7., 7., 7.],
        [8., 8., 8.],
        [9., 9., 9.]])

In [19]:
x_0stacked = torch.stack([x, x, x], dim=0)
x_0stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [1]:
x_original = torch.rand(size=(224, 224, 3))
x_permuted = x_original.permute(2, 0, 1)

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

NameError: name 'torch' is not defined

In [3]:
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [6]:
x[:, 0]

tensor([[1, 2, 3]])

In [10]:
x[:, :, 0]

tensor([[1, 4, 7]])